IS_TWITTER_MOCK_KEY = "IS_TWITTER_MOCK"
TWITTER_BEARER_TOKEN_KEY = "TWITTER_BEARER_TOKEN"
TWITTER_KEYWORDS_KEY = "TWITTER_KEYWORDS"
TWITTER_HASHTAGS_KEY = "TWITTER_HASHTAGS"
TWITTER_MAX_RESULTS_PER_REQUEST_KEY = "TWITTER_MAX_RESULTS_PER_REQUEST"
TWITTER_RATE_LIMIT_IN_SECONDS_KEY = "TWITTER_RATE_LIMIT_IN_SECONDS"
REDDIT_CLIENT_ID_KEY = "REDDIT_CLIENT_ID"
REDDIT_CLIENT_SECRET_KEY = "REDDIT_CLIENT_SECRET"
REDDIT_USERNAME_KEY = "REDDIT_USERNAME"
REDDIT_PASSWORD_KEY = "REDDIT_PASSWORD"
REDDIT_SUBREDDITS_KEY = "REDDIT_SUBREDDITS"
REDDIT_MAX_RESULTS_PER_REQUEST_KEY = "REDDIT_MAX_RESULTS_PER_REQUEST"
REDDIT_RATE_LIMIT_IN_SECONDS_KEY = "REDDIT_RATE_LIMIT_IN_SECONDS"

if __name__ == "__main__":
    pass
